import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { createRequire } from "module";
import path from "path";

const require = createRequire(import.meta.url);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const wsNodePath = path.resolve(path.dirname(require.resolve("ws/package.json")), "index.js");

const wsPlugin = {
	name: "force-ws-node",
	setup(build) {
		build.onResolve({ filter: /^ws$/ }, () => {
			return { path: wsNodePath, external: false };
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [wsPlugin],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
		"@electron/remote",
	],
	mainFields: ["module", "main"],
	conditions: ["node"],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	loader: {
		".svg": "text",
		".tsx": "tsx",
		".jsx": "jsx",
	},
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
